const fs = require('fs');
const path = require('path');
const config = require('../config');
const WorkspaceService = require('./WorkspaceService');

class GeminiService {
  constructor() {
    this.defaultModel = 'gemini-1.5-flash';
  }

  getConfigPath() {
    const root = WorkspaceService.workspaceRoot || config.WORKSPACE_ROOT;
    const teamDir = path.join(root, '_Team');
    if (!fs.existsSync(teamDir)) {
      try { fs.mkdirSync(teamDir, { recursive: true }); } catch (e) {}
    }
    return path.join(teamDir, 'ai-config.json');
  }

  getFallbackConfigPath() {
    return path.join(__dirname, '../ai-config.json');
  }

  getApiKey() {
    // 1. Check environment variable
    if (process.env.GEMINI_API_KEY) {
      return process.env.GEMINI_API_KEY.trim();
    }

    // 2. Check _Team/ai-config.json in workspace root
    const configPath = this.getConfigPath();
    if (fs.existsSync(configPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(configPath, 'utf8'));
        if (data.apiKey) return data.apiKey.trim();
      } catch (err) {
        console.warn('[GeminiService] Could not read primary ai-config.json:', err.message);
      }
    }

    // 3. Check fallback local path
    const fallbackPath = this.getFallbackConfigPath();
    if (fs.existsSync(fallbackPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(fallbackPath, 'utf8'));
        if (data.apiKey) return data.apiKey.trim();
      } catch (err) {
        console.warn('[GeminiService] Could not read fallback ai-config.json:', err.message);
      }
    }

    return '';
  }

  saveApiKey(apiKey, preferredModel = 'gemini-1.5-flash') {
    const payload = {
      apiKey: (apiKey || '').trim(),
      preferredModel: preferredModel || 'gemini-1.5-flash',
      updatedAt: new Date().toISOString()
    };
    const content = JSON.stringify(payload, null, 2);
    let saved = false;

    // Try primary workspace location
    try {
      const configPath = this.getConfigPath();
      fs.writeFileSync(configPath, content, 'utf8');
      saved = true;
    } catch (err) {
      console.warn('[GeminiService] Primary config write warning:', err.message);
    }

    // Also write to local fallback
    try {
      const fallbackPath = this.getFallbackConfigPath();
      fs.writeFileSync(fallbackPath, content, 'utf8');
      saved = true;
    } catch (err) {
      console.warn('[GeminiService] Fallback config write warning:', err.message);
    }

    return saved;
  }

  getStatus() {
    const key = this.getApiKey();
    let preferredModel = this.defaultModel;
    const configPath = this.getConfigPath();
    if (fs.existsSync(configPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(configPath, 'utf8'));
        if (data.preferredModel) preferredModel = data.preferredModel;
      } catch (e) {}
    }

    return {
      configured: Boolean(key && key.length > 5),
      maskedKey: key ? `${key.substring(0, 6)}...${key.substring(key.length - 4)}` : '',
      preferredModel,
      availableModels: ['gemini-1.5-flash', 'gemini-1.5-pro']
    };
  }

  /**
   * Calls Google Gemini REST API using native fetch.
   */
  async callGemini(systemPrompt, userPrompt, modelOverride = null) {
    const apiKey = this.getApiKey();
    if (!apiKey) {
      throw new Error('Gemini API key is not configured. Please set your Google AI Studio key in AI Settings.');
    }

    const model = modelOverride || this.getStatus().preferredModel || this.defaultModel;
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const body = {
      systemInstruction: {
        parts: [{ text: systemPrompt }]
      },
      contents: [
        {
          role: 'user',
          parts: [{ text: userPrompt }]
        }
      ],
      generationConfig: {
        temperature: 0.7,
        topP: 0.95,
        maxOutputTokens: 2048
      }
    };

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });

    if (!response.ok) {
      const errText = await response.text();
      let msg = `Gemini API error (${response.status})`;
      try {
        const errJson = JSON.parse(errText);
        if (errJson.error && errJson.error.message) msg = errJson.error.message;
      } catch (e) {}
      throw new Error(msg);
    }

    const json = await response.json();
    const candidate = json.candidates && json.candidates[0];
    if (!candidate || !candidate.content || !candidate.content.parts) {
      throw new Error('No response generated by Gemini model.');
    }

    return candidate.content.parts.map(p => p.text).join('\n').trim();
  }

  // ─── HIGH-CONVERTING BRAND ENGINES ──────────────────────────────────

  async generateHooks({ brand = 'SSH', product = 'Men Health Formulation', audience = 'Men aged 28-55', angle = 'Pain Point', language = 'Malay' }) {
    const systemPrompt = `You are a world-class direct-response copywriter for "SuamiSihat" brand holding company in Malaysia.
Your task is to write high-converting, viral advertising hooks that capture attention within the first 3 seconds on TikTok, Facebook, and Instagram Reels.
Language requirement: ${language === 'Malay' ? 'Bahasa Melayu yang santai, persuasive, dan natural (bukan kaku)' : 'High-impact persuasive English with local nuance'}.
Always provide 5 distinct categorized hooks:
1. 💥 CURIOSITY / PATTERN INTERRUPT
2. ⚡ PAIN POINT / AGITATION
3. 🏆 SOCIAL PROOF / TRANSFORMATION
4. ⏰ URGENCY / FOMO
5. 📖 RELATABLE STORYTELLING

Format as clean, ready-to-use markdown bullets with strong emojis.`;

    const userPrompt = `Brand: ${brand} (SuamiSihat holding)
Product / Campaign: ${product}
Target Audience: ${audience}
Primary Angle: ${angle}

Generate the 5 categorized viral hooks now:`;

    return await this.callGemini(systemPrompt, userPrompt);
  }

  async generateAdScript({ brand = 'SSH', product = 'Supplements', hook = '', platform = 'Meta Feed', language = 'Malay' }) {
    const systemPrompt = `You are an elite creative director and conversion copywriter for SuamiSihat health & lifestyle brands.
Write a full, ready-to-run advertising script optimized specifically for ${platform}.
Include:
- 🎣 Opening Hook (with visual text-on-screen cues)
- 🔥 Agitation & Problem Breakdown
- 💡 Solution & Mechanism of Action
- 🛡️ Medical / Regulatory Disclaimer (KKM / Halal / Natural compliant)
- 🚀 Strong Call to Action (CTA) with WhatsApp / Web checkout urgency

Language: ${language}. Use clean Markdown suitable for direct insertion into COPY.md.`;

    const userPrompt = `Brand: ${brand}
Product: ${product}
Selected Opening Hook: ${hook || 'Auto-generate strong hook'}
Platform: ${platform}

Write the complete high-converting copy script:`;

    return await this.callGemini(systemPrompt, userPrompt);
  }

  async generateImagePrompts({ product = 'Product packaging', style = 'Photorealistic Studio', environment = 'Minimalist Luxury Dark Mode', brandColors = '#D4AF37 Gold, #043388 Blue' }) {
    const systemPrompt = `You are a commercial 3D packaging and studio photographer prompt engineer specializing in Midjourney v6 and Google Imagen 3 prompts.
Generate 4 distinct, hyper-realistic commercial photography prompt variations for advertising mockups, social media creative banners, and packaging.
For each prompt, include:
- Prompt text (with lighting, camera lens e.g., 85mm f/1.4, volumetric lighting, Octane render details)
- Aspect ratio tag (e.g., --ar 1:1, --ar 9:16, --ar 16:9)
- Visual Style notes`;

    const userPrompt = `Product: ${product}
Style: ${style}
Environment / Backdrop: ${environment}
Brand Color Accents: ${brandColors}

Generate the 4 commercial image prompt variations:`;

    return await this.callGemini(systemPrompt, userPrompt);
  }

  formatUltraWebPrompt({ brand = 'SSH', title = 'Product Campaign', audience = 'Men 30-50', goal = 'High CTR Direct Response' }) {
    return `# SUAMISIHAT CREATIVE CAMPAIGN PROMPT FOR GEMINI ULTRA

You are the Lead Creative Director for **${brand} (SuamiSihat Group)**.

## Project Context:
- **Campaign Title**: ${title}
- **Brand Line**: ${brand}
- **Target Demographic**: ${audience}
- **Primary Objective**: ${goal}

## Brand & Compliance Guidelines:
1. **Tone**: Confident, empathetic, authoritative yet conversational (Bahasa Melayu / English).
2. **Compliance**: Avoid over-promising absolute cures; emphasize holistic wellness, premium natural active ingredients, lab-tested formulations, and real user confidence.
3. **Pacing**: Rapid-fire hook within first 3 seconds, concise agitation, clear transformation, and a single frictionless CTA.

## Request:
Please generate:
1. **5 Viral Opening Hooks** (Curiosity, Pain-Point, Proof, Urgency, Story).
2. **Full Video/Feed Script** with visual scene directions [Scene: ...] and audio voiceover script.
3. **3 WhatsApp Direct-Response Closing Messages** with interactive numbered options.
`;
  }
}

module.exports = new GeminiService();
